name: kiki
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  auto_size_text: ^2.1.0
  google_sign_in: ^4.5.3
  custom_radio_grouped_button: ^1.0.6+1
  searchable_dropdown: ^1.1.3
  geolocator: ^6.1.14
  geocoder: ^0.2.1
  toggle_switch: ^0.1.8
  image_picker:  ^0.6.7+22
  firebase_storage: 4.0.0
  cached_network_image: ^2.2.0
  video_thumbnail: ^0.2.5+1
  flutter_cache_manager: ^1.3.0
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.10
  intl: ^0.16.1
  firebase_messaging: 7.0.0
  flutter_local_notifications: 1.4.4+4
  photo_view: ^0.10.2
  video_player: ^0.10.11+2
  flutter_rounded_date_picker: ^1.0.5+1
  lite_rolling_switch: ^0.1.1
  tflite_flutter: ^0.5.0
  camera: ^0.5.8+5
  path_provider:
  path:
  firebase_ml_vision: ^0.9.6+2
  image:
  flutter_downloader: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/mobilefacenet.tflite
    - images/
    - assets/

  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/Mali-Regular.ttf
    - family: PottaOne
      fonts:
        - asset: fonts/PottaOne-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf



